# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from main import *
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(461, 276)
        self.textEdit = QtWidgets.QTextEdit(parent=Dialog)
        self.textEdit.setGeometry(QtCore.QRect(60, 50, 361, 31))
        self.textEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.textEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDigitsOnly|QtCore.Qt.InputMethodHint.ImhMultiLine)
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton.setGeometry(QtCore.QRect(190, 180, 91, 31))
        self.pushButton.clicked.connect(self.solve)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.initial_state_label = QtWidgets.QLabel(parent=Dialog)
        self.initial_state_label.setGeometry(QtCore.QRect(110, 20, 251, 21))
        self.initial_state_label.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.initial_state_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.initial_state_label.setObjectName("initial_state_label")
        self.radioButton = QtWidgets.QRadioButton(parent=Dialog)
        self.radioButton.setGeometry(QtCore.QRect(120, 140, 51, 21))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=Dialog)
        self.radioButton_2.setGeometry(QtCore.QRect(300, 140, 41, 21))
        self.radioButton_2.setObjectName("radioButton_2")
        self.option_label = QtWidgets.QLabel(parent=Dialog)
        self.option_label.setGeometry(QtCore.QRect(110, 100, 241, 21))
        self.option_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.option_label.setObjectName("option_label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "SOLVE"))
        self.initial_state_label.setText(_translate("Dialog", "Enter the initial state of the 8 puzzle solver"))
        self.radioButton.setText(_translate("Dialog", "BFS"))
        self.radioButton_2.setText(_translate("Dialog", "A*"))
        self.option_label.setText(_translate("Dialog", "Select the algorithm to solve the 8 puzzle solver"))
    def solve(self):
        print("Solving")
        initial_state = [int(x) for x in str(self.textEdit.toPlainText())]
        solver = main(initial_state)
        if self.radioButton.isChecked():
            solver.bfs_solver()
        elif self.radioButton_2.isChecked():
            solver.astar_solver()
        else:
            print("Select an option")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())